import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Image from "next/image";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen`}
//       >
//         <nav className="flex p-2 ml-10 sticky top-0 text-black ">
//           <Image src="/images/logo.png" alt="logo" height={80} width={80} />
//           <div className="flex ml-5 mt-7 text-2xl justify-between gap-x-4">
//             <p className="text-2xl font-bold  ">Red Apron</p>
//             <Link href="/">Home</Link>
//             <Link href="/sign in ">sign in </Link>
//           </div>
//           <div className="ml-auto mt-7 ">
//             <Link href="/sign in ">
//               <svg
//                 xmlns="http://www.w3.org/2000/svg"
//                 width="50"
//                 height="50"
//                 fill="orange"
//                 className="bi bi-person"
//                 viewBox="0 0 16 16"
//               >
//                 <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z" />
//               </svg>
//             </Link>
//           </div>
//         </nav>

//         {children}
//       </body>
//     </html>
//   );
// }

// here i let chat help me to modify layout and let the person icon to be on the right side
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-white min-h-screen`}
      >
        <nav className="flex items-center p-2 sticky top-0 text-black">
          {/* Logo and links */}
          <div className="flex items-center gap-x-4 text-2xl font-bold">
            <Link href="/">
              {" "}
              <Image src="/images/logo.png" alt="logo" height={80} width={80} />
            </Link>

            <p>Red Apron</p>
          </div>

          {/* Person Icon pushed to the right */}
          <div className="ml-auto">
            <Link href="/signIn">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="32"
                height="32"
                className="bi bi-person fill-red-700"
                viewBox="0 0 16 16"
              >
                <path d="M8 8a3 3 0 1 0 0-6 3 3 0 0 0 0 6m2-3a2 2 0 1 1-4 0 2 2 0 0 1 4 0m4 8c0 1-1 1-1 1H3s-1 0-1-1 1-4 6-4 6 3 6 4m-1-.004c-.001-.246-.154-.986-.832-1.664C11.516 10.68 10.289 10 8 10s-3.516.68-4.168 1.332c-.678.678-.83 1.418-.832 1.664z" />
              </svg>
            </Link>
          </div>
        </nav>

        {children}
      </body>
    </html>
  );
}
